Repository rohitdasu/projectmate, pull requests merged in 2022-10, with the labels that each got.

#195 added a loader in project submit
  pages/projects/submit.tsx
  public/loading.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#197 Added Infinite scroll
  components/Projects/ProjectsList.tsx
  pages/api/project/index.ts
Labels: enhancement, frontend, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#202 chore/add-prettier-linter-tailwindcss
  components/AuthModal/AuthModal.tsx
  components/Avatar/Avatar.tsx
  components/Avatar/SidebarAvatar.tsx
  components/FloatingButtonMenu/FloatingMenu.tsx
  components/Layouts/SharedLayout.tsx
  components/Projects/Project.tsx
  components/Projects/ProjectSkeleton.tsx
  components/Projects/ProjectsList.tsx
  components/Projects/Tags.tsx
  components/Search/Search.tsx
  components/ThemeToggler/ThemeToggler.tsx
  components/Topbar/DesktopRoutes.tsx
  components/Topbar/Logo.tsx
  components/Topbar/Sidebar.tsx
  components/Topbar/SocialLinks.tsx
  components/Topbar/Topbar.tsx
  package-lock.json
  package.json
  pages/about.tsx
  pages/index.tsx
  pages/projects/index.tsx
  pages/projects/submit.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#201 Fix: Replace 'any' and make strongly typed components
  interfaces/schema/postSchema.ts
  lib/httpResponse.ts
  pages/projects/submit.tsx
  prisma/schema.prisma
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#206 closes#199 add hover effect on social links and theme toggle
  components/ThemeToggler/ThemeToggler.tsx
  components/Topbar/SocialLinks.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#207 Replace fetch with axios
  components/Projects/ProjectsList.tsx
  package-lock.json
  package.json
  pages/about.tsx
  pages/projects/submit.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#208 hero section
  .eslintrc.json
  components/LandingPage/Hero.tsx
  components/LandingPage/index.ts
  components/LandingPage/lotties/hero.json
  pages/index.tsx
  public/animation-lottie.json
  styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#203 Closes #191- Added Project Form Validation based on issues/191
  components/ThemeToggler/ThemeToggler.tsx
  components/ThemeToggler/utils.tsx
  components/Toster/Toaster.tsx
  components/Toster/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/projects/submit.tsx
  public/loading.json
  styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#210 Landing page
  components/LandingPage/About.tsx
  components/LandingPage/Benefit.tsx
  components/LandingPage/Guide.tsx
  components/LandingPage/Hero.tsx
  components/LandingPage/assets/learning.jpg
  components/LandingPage/assets/portfolio.jpg
  components/LandingPage/data.ts
  components/LandingPage/index.ts
  components/Layouts/SharedLayout.tsx
  components/Topbar/data.ts
  pages/about.tsx
  pages/index.tsx
  pages/projects/index.tsx
  styles/globals.css
Labels: enhancement, frontend, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#211 Recreating design look for profile page
  components/Avatar/Avatar.tsx
  components/Avatar/SidebarAvatar.tsx
  pages/profile.tsx
  pages/user/profile.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#215 added blog section
  components/Topbar/data.ts
  pages/blog/index.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#214 fixed layout issue
  components/Layouts/SharedLayout.tsx
  pages/index.tsx
  pages/user/profile.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#223 Replace plain text icon with lottie animation in blog page
  pages/blog/index.tsx
  public/comingSoon.json
Labels: good first issue, frontend, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#225 Updated the loader lottie animation color
  public/loading.json
Labels: good first issue, frontend, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#222 feat: added Rich Text Editor
  package-lock.json
  package.json
  pages/projects/submit.tsx
  styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#229 improve project submit page
  components/Form/FileDrop/FileDrop.tsx
  components/Form/FileDrop/index.ts
  components/Form/Input/Input.tsx
  components/Form/Input/index.ts
  components/Form/RichTextEditor/RichTextEditor.tsx
  components/Form/RichTextEditor/index.ts
  components/SubmitPageForm/SubmitPageForm.tsx
  components/SubmitPageForm/index.ts
  components/SubmitPageForm/schema.ts
  package-lock.json
  package.json
  pages/projects/submit.tsx
  shared/index.ts
  styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#233 Fixed line break in project component
  components/Projects/Project.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#242 235 chore remove image field from projects
  components/Form/FileDrop/FileDrop.tsx
  components/Form/FileDrop/index.ts
  components/Projects/Project.tsx
  components/Projects/ProjectSkeleton.tsx
  components/Projects/ProjectsList.tsx
  components/Search/Search.tsx
  components/SubmitPageForm/SubmitPageForm.tsx
  pages/projects/[projectId].tsx
  pages/projects/index.tsx
  public/open-source.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#243 Get user projects
  pages/api/user/project.ts
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#244 fix: light mode color for profile page
  components/Profile/Project/Project.tsx
  components/Profile/Project/index.ts
  components/index.ts
  pages/user/profile.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#246 feat: integrated projects by user api with frontend
  pages/user/profile.tsx
  public/error.json
  public/no-data.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#216 Closes#188 Content column added to project API
  components/Form/RichTextEditor/RichTextEditor.tsx
  components/SubmitPageForm/SubmitPageForm.tsx
  interfaces/schema/postSchema.ts
  package-lock.json
  pages/api/project/index.ts
  prisma/schema.prisma
  prisma/seed.ts
  public/comingSoon.json
  public/loading.json
  styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#252 Fix for tags not displaying correct value in project details issue
  pages/projects/[projectId].tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#253 Update axios version
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#254 added twitter logo in topbar
  components/Topbar/data.ts
Labels: frontend, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#255 improve: projects card animation
  components/Projects/Project.tsx
  components/Projects/ProjectSkeleton.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#257 fix: color adjusted to match theme
  components/FloatingButtonMenu/FloatingButtonMenu.interface.ts
  components/FloatingButtonMenu/FloatingMenu.tsx
  components/LandingPage/Hero.tsx
  components/Projects/Project.tsx
  components/Projects/Tags.tsx
  components/SubmitPageForm/SubmitPageForm.tsx
  pages/projects/[projectId].tsx
  pages/projects/index.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#256 Improve projects page accessibility
  components/Profile/Project/Project.tsx
  components/Projects/Project.tsx
  components/Projects/ProjectsList.tsx
  pages/user/profile.tsx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#237 Changed framerate speed from Hero animation to 23.976
  components/LandingPage/lotties/hero.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
