Repository rohitdasu/projectmate, pull requests merged in 2022-09, with the labels that each got.

#109 chore: removed mongodb
  README.md
  lib/firebase.ts
  lib/mongodb.js
  pages/api/home.ts
  pages/api/projects.ts
Labels: enhancement

#110 feat: added tooltip to nav icons
  components/Navbar/Navbar.tsx
  components/Tooltip/Tooltip.tsx
Labels: enhancement, frontend

#118 115 feature add add project button to the app
  README.md
  components/Projects/Project.tsx
  package-lock.json
  package.json
  pages/projects.tsx
Labels: frontend

#122 feature: add project form
  components/Avatar/Avatar.tsx
  pages/projects.tsx
Labels: enhancement, frontend

#139 fix: improved project card and buttons
  components/Projects/Project.tsx
  pages/index.tsx
  public/open-source.png
Labels: enhancement, frontend, hacktoberfest, hacktoberfest-accepted

#182 feat: added animations
  components/Avatar/Avatar.tsx
  components/Projects/Project.tsx
  components/Topbar/DesktopRoutes.tsx
  components/Topbar/Logo.tsx
  components/Topbar/Sidebar.tsx
  pages/index.tsx
  pages/profile.tsx
  pages/projects/submit.tsx
Labels: enhancement

#185 fix social media links
  components/Topbar/DesktopRoutes.tsx
  components/Topbar/Sidebar.tsx
  components/Topbar/SocialLinks.tsx
  components/Topbar/Topbar.tsx
  components/Topbar/data.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
